### PR TITLE
Fix array global iterator

### LINKED ISSUE #108: Fix iterator movements in array when distributed.

### PR DESCRIPTION
**Pull request by mminutoli**
This fixes #108 .  Now UT run successfully on our cluster.

### CODE REVIEW

**Comment by mminutoli** [comment]
@VitoCastellana Check if this is actually fixing also your issues with the array.

File: include/shad/data_structures/array.h [hunk 1]
```diff
@@ -1183,15 +1183,7 @@ class array : public AbstractDataStructure<array<T, N>> {
...
-
-    pointer chunk = nullptr;
-    rt::executeAtWithRet(rt::Locality(0),
-                         [](const ObjectID &ID, pointer *result) {
-                           auto This = array<T, N>::GetPtr(ID);
-                           *result = This->chunk_.get();
-                         },
-                         GetGlobalID(), &chunk);
-    return iterator(rt::Locality(0), 0, oid_, chunk);
+    return iterator(rt::Locality(0), 0, oid_, nullptr);
```
Comment (droccom) [inline include/shad/data_structures/array.h]: for uniformity with line 1184:
`return iterator{rt::Locality(0), 0, oid_, nullptr};`

File: include/shad/data_structures/array.h [hunk 2]
```diff
@@ -1623,6 +1621,11 @@ class alignas(64) array<T, N>::ArrayRef<const U>
 
   ArrayRef(ArrayRef &&O) : array<T, N>::template BaseArrayRef<U>(O) {}
 
+  bool operator==(const ArrayRef &&v) const {
+    if (array<T, N>::template BaseArrayRef<U>::operator==(v)) return true;
+    return false;
+  }
```
Comment (droccom) [inline include/shad/data_structures/array.h]: `return array<T, N>::template BaseArrayRef<U>::operator==(v);`
